## SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0
---
linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - funlen
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
  disable:
    - errcheck
    - ineffassign

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen

linters-settings:
  misspell:
    locale: US
  errorlint:
    # Report non-wrapping error creation using fmt.Errorf
    errorf: false
  funlen:
    lines: 60
    statements: 60
